### ISSUE TITLE
Not working properly inside ScrollView

### ISSUE THREAD

**Issue by ritesh24** [Manabu-GT/ExpandableTextView#15]
Hi I am using ExpandableTextView inside ScrollView. It is not behaving as it should. Please take a look
![etv2](https://cloud.githubusercontent.com/assets/1598688/6672377/24275642-cc32-11e4-8a0d-732ee715cdb2.gif)

**Comment by DrDuke** [comment]
Manabu, first of all: Thank you for writing this code ^_^

I was experiencing the same issue (in a ScrollView also) but then I tried to put the code in a simple activity with a LinearLayout and the same happens.
Then I checked the compile version and mine is 19 with buildTools 19, meanwhile this library is compiled against 21 (and you need JDK 7 for that task) so I guess the problem is around there ;)

**Comment by DrDuke** [comment]
Ritesh,
I tried  to update the code and nothing 
Fiinally I discovered I was setting the TextView with setText("blablabla"). 
Instead, the ExpandableTextView should be the one set.

**Comment by Manabu-GT** [comment]
@ritesh24 Thank you for using my library. Is this issue still not resolved? Based on DrDuke's comment, I am wondering I should still look into this one. If the issue is still occurring, please share the entire layout xml file you are using for ExapandableTextView.

**Comment by squeeish** [comment]
I keep running into this issue, where I inadvertently set text to the inner textview instead of the overall expand_text_view. The README.md should include this caveat. :)

**Comment by Manabu-GT** [comment]
The README.md should include this caveat. :)
-> Thank you for your feedback. I just updated the README to point that out.
